# Generated by Django 6.1.1 on 2026-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(max_length=6)),
                ('result_file', models.FileField(upload_to='results')),
                ('n_rows', models.PositiveIntegerField()),
            ],
        ),
    ]
