# Generated by Django 6.1.1 on 2026-10-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='n_rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queryresult',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
