# Generated by Django 6.1.1 on 2026-10-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_queryresult_n_rows_queryresult_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryresult',
            name='success',
        ),
    ]
